#define CHORDAL_HOLD
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "4vAOM/6aqAMN"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define RGB_MATRIX_STARTUP_SPD 60
#define MOUSE_JIGGLER_MOVEMENT 20
